server:
  port: 8080

app:
    api:
        prefix: /api/v1
        prefixAI: http://127.0.0.1:8000
    security:
      expiresIn: 6000 # 300 second = 5 minutes
      expiresRefresh: 30000 # 3000 second = 50p
      secret: fEJ6qu3MQ1pwdpRYxhiXNpor7jNV6tCdhw73m9rR5TfH5rS6Zq1tVDsUooXljGi3
    clodinary:
      url: cloudinary://673758235311112:lQ-W_bCswUJHcqmGXVenasImLnY@dqtj816ds
    file:
      prefix: /uploads
vnpay:
  tmn-code: 0D7U0C4Z
  hash-secret: 8ZF37DFFNM6F4M756V6PA2MW4UO75DM4
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/v1/payment/vnpay/return

spring:
    application:
        name: medical_store
    profiles:
        active: dev